export const productActions = {
    PRODUCTS_REQUEST : "PRODUCTS_REQUEST",
    PRODUCTS_SUCCESS : "PRODUCTS_SUCCESS",
    PRODUCTS_FAIL : "PRODUCTS_FAIL",

    SINGLE_PRODUCT_REQUEST : "SINGLE_PRODUCT_REQUEST",
    SINGLE_PRODUCT_SUCCESS : "SINGLE_PRODUCT_SUCCESS",
    SINGLE_PRODUCT_FAIL : "SINGLE_PRODUCT_FAIL",

    RELATED_PRODUCT_REQUEST : "RELATED_PRODUCT_REQUEST",
    RELATED_PRODUCT_SUCCESS : "RELATED_PRODUCT_SUCCESS",
    RELATED_PRODUCT_FAIL : "RELATED_PRODUCT_FAIL",
}